create database LINHKIENMAYTINH;

CREATE TABLE DANHMUCLOAIHANG (
MADM INT IDENTITY(1,1) PRIMARY KEY,
TENDM NVARCHAR(50),
CREATE_AT DATE DEFAULT Convert(date, GETDATE())
)

CREATE TABLE LOAIHANG (
MALOAIHANG INT IDENTITY(1,1) PRIMARY KEY,
TENHANG NVARCHAR(50),
MADM INT,
CREATE_AT DATE DEFAULT Convert(date, GETDATE())
)

CREATE TABLE NHANVIEN (
MANV INT IDENTITY(1,1) PRIMARY KEY,
USERNAM NVARCHAR(30) ,
PASSWORK NVARCHAR(30),
HOTEN NVARCHAR(50),
SDT NVARCHAR(11),
DIACHI NVARCHAR(50),
NAMSINH DATE,
LOAINV NVARCHAR(30),
GIOITINH NVARCHAR(10),
CREATE_AT DATE DEFAULT Convert(date, GETDATE())
)

CREATE TABLE KHACHHANG (
MAKH INT IDENTITY(1,1) PRIMARY KEY,
TENKH NVARCHAR(50),
SDT NVARCHAR(30),
NAMSINH DATE,
CREATE_AT DATE DEFAULT Convert(date, GETDATE())
)

CREATE TABLE HANG (
MAHANG INT IDENTITY(1,1) PRIMARY KEY,
THONGSO TEXT ,
BAOHANH INT ,
SOLUONG INT,
GIA INT,
HINH NVARCHAR(MAX) DEFAULT 'hinhmacdinh',
MALOAIHANG INT,
CREATE_AT DATE DEFAULT Convert(date, GETDATE())
)


CREATE TABLE BIENLAI (
MABIENLAI INT IDENTITY(1,1) PRIMARY KEY,
MAKH INT,
MANV INT,
CREATE_AT DATE DEFAULT Convert(date, GETDATE())
)

CREATE TABLE CHITIETBIENLAI (
MACTBL INT IDENTITY(1,1) PRIMARY KEY,
MABIENLAI INT,
MAHANG INT,
CREATE_AT DATE DEFAULT Convert(date, GETDATE())
)