CREATE DATABASE QL_LINHKIEN
use QL_LINHKIEN


CREATE TABLE DANHMUC (
MADM INT IDENTITY(1,1) PRIMARY KEY,
TENDANHMUC NVARCHAR(50),
NGAYTAO DATE DEFAULT GETDATE() )

CREATE TABLE NHACUNGCAP (
MANCC INT IDENTITY (1,1) PRIMARY KEY,
TENNCC NVARCHAR(50),
DIACHI NVARCHAR(80),
FAX CHAR(10),
EMAIL VARCHAR(50),
NGAYTAO DATE DEFAULT GETDATE())

CREATE TABLE HANG (
MAHANG INT IDENTITY(1,1) PRIMARY KEY,
TENHANG VARCHAR(50),
THONGSO NVARCHAR(200),
BAOHANH INT,
SOLUONG INT,
GIA INT,
HINH VARCHAR(100) DEFAULT 'default.png',
NHASANXUAT VARCHAR(50),
NGAYTAO DATE DEFAULT GETDATE(),
MADANHMUC INT FOREIGN KEY REFERENCES DANHMUC(MADM))

CREATE TABLE NHANVIEN (
MANV INT IDENTITY(1,1) PRIMARY KEY,
USERNAME VARCHAR(50),
PASSWORD VARCHAR(80),
HOTEN NVARCHAR(50),
SDT CHAR(10),
DIACHI NVARCHAR(80),
NAMSINH DATE,
LOAINHANVIEN TINYiNT,
GIOITINH BIT,
NGAYTAO DATE DEFAULT GETDATE())

CREATE TABLE KHACHHANG (
MAKH INT IDENTITY(1,1) PRIMARY KEY,
HOTEN NVARCHAR(50),
SDT CHAR(10),
NAMSINH DATE,
NGAYTAO DATE DEFAULT GETDATE())

CREATE TABLE PHIEUNHAP (
MAPHIEUNHAP INT IDENTITY(1,1) PRIMARY KEY,
NGAYTAO DATE DEFAULT GETDATE(),
MANCC INT FOREIGN KEY REFERENCES NHACUNGCAP(MANCC),
MANV INT FOREIGN KEY REFERENCES NHANVIEN(MANV))

CREATE TABLE CHITIETPHIEUNHAP (
MAPHIEUNHAP INT FOREIGN KEY REFERENCES PHIEUNHAP(MAPHIEUNHAP),
MAHANG INT FOREIGN KEY REFERENCES HANG(MAHANG),
SOLUONG INT,
GIANHAP INT,
PRIMARY KEY(MAPHIEUNHAP,MAHANG))


CREATE TABLE PHIEUXUAT (
MAPHIEUXUAT INT IDENTITY(1,1) PRIMARY KEY,
MAKH INT FOREIGN KEY REFERENCES  KHACHHANG(MAKH) null,
NGAYTAO DATE DEFAULT GETDATE(),
MANV INT FOREIGN KEY REFERENCES NHANVIEN(MANV))

CREATE TABLE CHITIETPHIEUXUAT (
MAPHIEUXUAT INT FOREIGN KEY REFERENCES PHIEUXUAT(MAPHIEUXUAT),
MAHANG INT FOREIGN KEY REFERENCES HANG(MAHANG),
PRIMARY KEY(MAPHIEUXUAT,MAHANG),
SOLUONG INT,
GIAXUAT INT)




